# Generated by Django 3.0.6 on 2020-08-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='error',
            name='id',
        ),
        migrations.AddField(
            model_name='error',
            name='error_id',
            field=models.PositiveIntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
