# Generated by Django 3.0.6 on 2020-06-26 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Gellery', 'verbose_name_plural': 'Gelleries'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Reviews', 'verbose_name_plural': 'Reviews'},
        ),
    ]
