# Generated by Django 3.0.6 on 2020-06-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200626_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wishes',
            field=models.BooleanField(default=False),
        ),
    ]
