# Generated by Django 3.0.6 on 2020-07-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200718_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Username')),
                ('first_name', models.CharField(max_length=100, verbose_name='First name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('password', models.SlugField(max_length=100)),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is staff')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is active')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Is superuser')),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='Last login')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date joined')),
                ('date_registration', models.DateTimeField(auto_now_add=True, verbose_name='Date registration')),
            ],
        ),
    ]
