# Generated by Django 3.0.6 on 2020-07-18 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
