# Generated by Django 3.0.6 on 2020-07-18 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20200718_1400'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
