# Generated by Django 3.0.6 on 2020-08-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20200819_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
    ]
