# Generated by Django 3.0.6 on 2020-08-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20200820_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='class_for_css',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название класса для css'),
        ),
    ]
