# Generated by Django 3.0.6 on 2020-08-22 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_product_price_with_sale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='email',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='name',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='text_ru',
        ),
    ]
