# Generated by Django 3.0.6 on 2020-08-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20200824_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='quantity_of_likes',
            field=models.PositiveIntegerField(default=0, help_text='Начинается с 0', verbose_name='Число лайков'),
        ),
    ]
