# Generated by Django 3.0.6 on 2020-08-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_reviews_quantity_of_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='quantity_of_dislikes',
            field=models.PositiveIntegerField(default=0, help_text='Начинается с 0', verbose_name='Число дизлайков'),
        ),
    ]
