# Generated by Django 3.0.6 on 2020-08-24 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_reviews_quantity_of_dislikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dislike',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Reviews'),
        ),
        migrations.AlterField(
            model_name='like',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Reviews'),
        ),
    ]
