# Generated by Django 3.0.6 on 2020-08-25 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_auto_20200824_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='item',
        ),
        migrations.AddField(
            model_name='wish',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Product'),
        ),
    ]
