# Generated by Django 3.0.6 on 2020-08-25 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_auto_20200825_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product'),
        ),
    ]
