# Generated by Django 3.0.6 on 2020-08-26 09:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_auto_20200825_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата публикации'),
            preserve_default=False,
        ),
    ]
